import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter, Cinzel } from 'next/font/google'
import Footer from '@/components/Footer'
import Provider from '@/SessionProvider'


const inter = Inter({ subsets: ['latin'] })
const cinzel = Cinzel({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cinzel.className}>
      <Provider>
      <Navbar />
      {children}
      <Footer />
      </Provider>
      </body>
    </html>
  )
}
